language: r

sudo: required

warnings_are_errors: true

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
 - gdtools
 - covr

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel

after_script:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'covr::codecov()'
