language: r

sudo: required

warnings_are_errors: false

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

r_packages:
 - gdtools

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel

r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
