language: r

cache: packages

r_github_packages:
  - jimhester/covr

r:
 - oldrel
 - release
 - devel

matrix:
  include:
    # Ubuntu 12.04 LTS (Precise Pangolin)
    - os: linux
      dist: precise
    # Ubuntu 14.04.4 LTS (Trusty Tahr)
    - os: linux
      dist: trusty
    # Xcode 7.3.1 OS X 10.11
    - os: osx
      osx_image: xcode7.3
    # Xcode 7.1.1 GM  OS X 10.10
    - os: osx
      osx_image: xcode7.1
    # Xcode 7.1.1 GM  OS X 10.9
    - os: osx
      osx_image: beta-xcode6.1

after_success:
  - Rscript -e 'library(covr);codecov()'
