language: r

cache: packages

r_github_packages:
  - jimhester/covr

matrix:
  include:
    # Ubuntu 12.04 LTS (Precise Pangolin)
    - os: linux
      dist: precise
      r: release
    - os: linux
      dist: precise
      r: devel
    # Ubuntu 14.04.4 LTS (Trusty Tahr)
    - os: linux
      dist: trusty
      r: release
    - os: linux
      dist: trusty
      r: devel
    # Xcode 7.3.1 OS X 10.11
    - os: osx
      osx_image: xcode7.3
      r: devel
    - os: osx
      osx_image: xcode7.3
      r: release
    # Xcode 7.1.1 GM  OS X 10.10
    - os: osx
      osx_image: xcode7.1
      r: release
    - os: osx
      osx_image: xcode7.1
      r: devel
    # Xcode 7.1.1 GM  OS X 10.9
    - os: osx
      osx_image: beta-xcode6.1
      r: devel
    - os: osx
      osx_image: beta-xcode6.1
      r: release

after_success:
  - Rscript -e 'library(covr);codecov()'
