language: r

sudo: required

warnings_are_errors: false

os:
 - linux
 - osx


before_install:
if [[ "$os" == "osx" ]]; then brew update; brew install cairo; f

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - davidgohel/gdtools

env:
  matrix:
    - RVERSION=oldrel
    - RVERSION=release
    - RVERSION=devel


matrix:
  allow_failures:
    - os: osx
